/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ruleta;

import com.panamahitek.PanamaHitek_Arduino;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import uk.co.caprica.vlcj.binding.LibVlc;

import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author VBarrera
 */
public class VistaModificada extends JFrame {

    /**
     * Creates new form NewApplication
     */
    private EmbeddedMediaPlayerComponent playerLan;
    private EmbeddedMediaPlayerComponent playerAleatorio;
    private File file;

    static {
     
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:/Program Files/VideoLAN/VLC/");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
           System.load("C:/Program Files/VideoLAN/VLC/libvlc.dll");
        System.load("C:/Program Files/VideoLAN/VLC/libvlccore.dll");
    }
    PanamaHitek_Arduino puertoCom = new PanamaHitek_Arduino();
    SerialPortEventListener event = new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            if (puertoCom.isMessageAvailable()) {
                String dato = puertoCom.printMessage();
                System.out.println(dato);
                if (dato.equals("onlucky")) {
                    lucky();
                    try {
                        Thread.sleep(10000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }
    };

    //bandera para controlar la reproduccion de video y el cambio en el avance de video
    private boolean band = true;

    public VistaModificada() {
        initComponents();
        setAlwaysOnTop(true);
        puertoCom.showMessageDialogs(false);
        try {
            puertoCom.arduinoRX("COM1", 9600, event);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningún Boton conectado en el puerto . Verifique el puerto en el que está conectado");
//Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jButtonRandom.setVisible(false);
        setLocationRelativeTo(null);
        
        try {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            GraphicsDevice[] gs = ge.getScreenDevices();
            gs[1].setFullScreenWindow(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Software funciona solo en pantalla extendida.");
            System.exit(1);
        }
//        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
//        setBounds(getGraphicsConfiguration().getBounds());
//        getGraphicsConfiguration().getDevice().setFullScreenWindow(this);
        playerLan = new EmbeddedMediaPlayerComponent();
        //jPanelVideoLan.add(playerLan);
        //  playerLan.setSize(jPanelVideoLan.getSize());
//        playerLan.getMediaPlayer().enableOverlay(true);
//        playerLan.getMediaPlayer().playMedia("C:\\Media\\Movies\\lucky number Plazuela.jpg");
//        jLabelResultadoIzq.setText("");
//        jLabelResultadoDer.setText("");
        playerAleatorio = new EmbeddedMediaPlayerComponent();
        jButtonRandom.setFocusable(true);
        jPanelVideoAleatorio.add(playerAleatorio);
        playerAleatorio.setSize(600, 540);
        playerAleatorio.setVisible(true);
        file = new File("C:\\Media\\Movies\\principal.avi");
//        String absolutePath = file.getAbsolutePath();
//        String newPath = absolutePath.substring(0, absolutePath.length() - 4) + "_" + System.currentTimeMillis() + ".png";
//        System.out.println("" + file.getAbsolutePath());
        //if( player.getMediaPlayer().saveSnapshot(new File(newPath))) 
        playerAleatorio.getMediaPlayer().setRepeat(true);
        playerAleatorio.getMediaPlayer().playMedia(file.getAbsolutePath());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelVideoAleatorio = new javax.swing.JPanel();
        jButtonRandom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelResultadoDer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 102, 51));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanelPrincipal.setBackground(new java.awt.Color(153, 153, 0));
        jPanelPrincipal.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(600, 400));

        jPanelVideoAleatorio.setBackground(new java.awt.Color(255, 255, 102));
        jPanelVideoAleatorio.setOpaque(false);
        jPanelVideoAleatorio.setPreferredSize(new java.awt.Dimension(600, 540));

        javax.swing.GroupLayout jPanelVideoAleatorioLayout = new javax.swing.GroupLayout(jPanelVideoAleatorio);
        jPanelVideoAleatorio.setLayout(jPanelVideoAleatorioLayout);
        jPanelVideoAleatorioLayout.setHorizontalGroup(
            jPanelVideoAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelVideoAleatorioLayout.setVerticalGroup(
            jPanelVideoAleatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jButtonRandom.setText("Random");
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/imagenes/luckynumber.png"))); // NOI18N
        jLabel1.setRequestFocusEnabled(false);

        jLabelResultadoDer.setFont(new java.awt.Font("Arial", 1, 250)); // NOI18N
        jLabelResultadoDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultadoDer.setText("00");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelResultadoDer, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(439, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jButtonRandom)
                        .addGap(52, 52, 52))))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jPanelVideoAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(725, Short.MAX_VALUE)
                .addComponent(jLabelResultadoDer, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonRandom))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jPanelVideoAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        lucky();
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    jButtonRandom.setEnabled(false);
                    Thread.sleep(30000);
                    jButtonRandom.setEnabled(true);
                    System.out.println("Random");
                } catch (InterruptedException ex) {
                    Logger.getLogger(VistaModificada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed
    public void lucky() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                //jLabelResultadoIzq.setText("");
                //jLabelResultadoDer.setText("");
                try {

                    Random aleatorio = new Random();
                    int resultado = (0 + aleatorio.nextInt((37 + 1) - 0));
                    String datos = null;
                    datos = "" + resultado;
                    if (datos.length() == 1) {

                        if (datos == "0") {

                        } else {

                            datos = "0" + datos;
                            //System.out.println(".run() " + datos);
                        }
                    }
                    if (resultado == 37) {
                        datos = "" + resultado;

                    } else if (resultado == 0) {
                        datos = "00";

                    } else {
                        // datos = "" + resultado;

                    }
                    file = new File("C:\\Media\\Movies\\principal.avi");
                    playerAleatorio.getMediaPlayer().playMedia(file.getAbsolutePath());
                    //System.out.println("" + datos);
                    Thread.sleep(10000);
                    file = new File("C:\\Media\\Movies\\Win 1-1 DZ Mercury Pockets Mahogany\\win_" + datos + ".avi");
                    playerAleatorio.getMediaPlayer().playMedia(file.getAbsolutePath());
                    Thread.sleep(1000);
                    if (resultado == 37) {

                        //jLabelResultadoIzq.setText("00");
                        jLabelResultadoDer.setText("00");
                    } else if (resultado == 0) {

                        // jLabelResultadoIzq.setText("0");
                        jLabelResultadoDer.setText("0");
                    } else {

                        //  jLabelResultadoIzq.setText("" + resultado);
                        jLabelResultadoDer.setText("" + resultado);
                    }
                    Thread.sleep(7000);

                    file = new File("C:\\\\Media\\\\Movies\\lucky number Plazuela.jpg");
                    playerAleatorio.getMediaPlayer().playMedia(file.getAbsolutePath());

                } catch (InterruptedException ex) {
                    Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files (x86)\\VideoLAN\\VLC");
        //Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRandom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResultadoDer;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVideoAleatorio;
    // End of variables declaration//GEN-END:variables

}
